// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMBR3PNTRYZSQHIJyfUdWND98rOoBN_sg',
    appId: '1:286345996515:web:25eeb1bd80a0890246bdd6',
    messagingSenderId: '286345996515',
    projectId: 'denguard-works',
    authDomain: 'denguard-works.firebaseapp.com',
    storageBucket: 'denguard-works.firebasestorage.app',
    measurementId: 'G-YFFJ53GS0Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0vS7yQ4tpiM6_8kACGBBugcq3kfzbmZg',
    appId: '1:286345996515:android:fd82aaa4dde7aaca46bdd6',
    messagingSenderId: '286345996515',
    projectId: 'denguard-works',
    storageBucket: 'denguard-works.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2Ir2WkP09B5rHXDx6GjRwWM0-OkrNmgM',
    appId: '1:286345996515:ios:3d6979471106090a46bdd6',
    messagingSenderId: '286345996515',
    projectId: 'denguard-works',
    storageBucket: 'denguard-works.firebasestorage.app',
    iosBundleId: 'com.example.denguard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2Ir2WkP09B5rHXDx6GjRwWM0-OkrNmgM',
    appId: '1:286345996515:ios:3d6979471106090a46bdd6',
    messagingSenderId: '286345996515',
    projectId: 'denguard-works',
    storageBucket: 'denguard-works.firebasestorage.app',
    iosBundleId: 'com.example.denguard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMBR3PNTRYZSQHIJyfUdWND98rOoBN_sg',
    appId: '1:286345996515:web:9696e41e71e01e0f46bdd6',
    messagingSenderId: '286345996515',
    projectId: 'denguard-works',
    authDomain: 'denguard-works.firebaseapp.com',
    storageBucket: 'denguard-works.firebasestorage.app',
    measurementId: 'G-LF3VLGR0RH',
  );
}
